all:
  site:
    hosts:
      localhost:
        ansible_connection: local

  pfsense:
    hosts:
      10.7.2.91:
        ansible_connection: ssh

  windows:
    hosts:
      10.0.50.50:
        ansible_connection: ssh