
- name: Allow Internal DNS traffic out
  
  action: pass
  interface: lan
  ipprotocol: inet
  protocol: udp
  source: dns_int
  destination: any
  destination_port: 53
  after: 'Allow proxies out'
  state: present

  register: ping_result


- name: Ping result
  debug:
    msg: "{{ ping_result.stdout_lines }}"
