- name: Allow XMLRPC synchronization traffic on SYNC interface
  pfsensible.core.pfsense_rule:
    name: "Allow XMLRPC traffic on SYNC"
    action: pass
    interface: "escola"
    ipprotocol: inet
    protocol: tcp
    source: any
    destination: any
    destination_port: 9090
    state: present
  tags: rules
